# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ID - Bstation

on:
  workflow_dispatch:
  schedule:
    - cron: "00 3/6 * * *"
  
permissions:
  contents: read

jobs:
  fetch:
    runs-on: ubuntu-latest
    environment: public-sheet
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Load Credentials
      run: |
        mkdir -p credentials
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_CONTENT }}' > ${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILENAME }}
    - name: Fetch Indonesian VTubers
      env:
        SERVICE_ACCOUNT_FILE: ../../${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILENAME}}
        UTC_OFFSET: ${{ vars.UTC_OFFSET }}
        GOOGLE_SHEET_ID_SRC: ${{ secrets.ID_GOOGLE_SHEET_SRC }}
        GOOGLE_SHEET_ID_DEST: ${{ secrets.ID_GOOGLE_SHEET_DEST }}
        GOOGLE_SHEET_RANGE_SRC_USERNAME: ${{ vars.BS_GOOGLE_SHEET_RANGE_SRC_USERNAME }}
        GOOGLE_SHEET_RANGE_SRC_DATA: ${{ vars.BS_GOOGLE_SHEET_RANGE_SRC_DATA }}
        GOOGLE_SHEET_RANGE_DEST: ${{ vars.BS_GOOGLE_SHEET_RANGE_DEST }}
        BILIBILI_VERIFIED_URL: ${{ vars.BS_BILIBILI_VERIFIED_URL }}
      run: |
        mkdir -p csv/id && cd csv/id
        python ../../main_bilibili.py
        cd ..
    - uses: actions/upload-artifact@v3
      with:
        name: csv
        path: csv/
  