# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PH - Update Profiles

on:
  workflow_dispatch:
  schedule:
    - cron: "50 1/6 * * *"
  
permissions:
  contents: read

jobs:
  fetch:
    runs-on: ubuntu-latest
    environment: public-sheet
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Load Credentials
      run: |
        mkdir -p credentials
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_CONTENT }}' > ${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILENAME }}
    - name: Fetch data from 3rd party source
      env:
        SERVICE_ACCOUNT_FILE: ../../${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILENAME}}
        GOOGLE_SHEET_ID_SRC: ${{ secrets.PH_GOOGLE_SHEET_SRC }}
        GOOGLE_SHEET_ID_DEST: ${{ secrets.PH_GOOGLE_SHEET_DEST }}
      run: |
        mkdir -p csv/id/outputs && cd csv/id
        python ../../copy_profile.py
        cd ..
    - uses: actions/upload-artifact@v4
      with:
        name: csv
        path: csv/
  